export const SKILLS = [
  "JavaScript", "TypeScript", "Python", "Java", "C#", "C++", "C", "Ruby", "PHP", "Swift",
  "Kotlin", "Go", "Rust", "Dart", "Scala", "R", "Perl", "Objective-C", "Shell Scripting",
  "React", "Angular", "Vue.js", "Svelte", "Next.js", "Nuxt.js", "Gatsby", "Ember.js",
  "Node.js", "Express.js", "NestJS", "Django", "Flask", "FastAPI", "Spring Boot",
  "ASP.NET Core", "Ruby on Rails", "Laravel", "Symfony", "GraphQL", "REST APIs",
  "HTML5", "CSS3", "Sass", "Less", "Tailwind CSS", "Bootstrap", "Material UI", "Chakra UI",
  "Ant Design", "Framer Motion", "Three.js", "WebGL", "WebAssembly", "PWA", "Webpack",
  "Vite", "Rollup", "Parcel", "Babel", "ESLint", "Prettier", "Jest", "Mocha", "Chai",
  "Cypress", "Playwright", "Selenium", "Puppeteer", "Redux", "MobX", "Zustand", "Recoil",
  "React Query", "Apollo Client", "Vuex", "Pinia", "RxJS", "D3.js", "Chart.js", "SQL",
  "PostgreSQL", "MySQL", "SQLite", "SQL Server", "Oracle", "MongoDB", "Cassandra",
  "Couchbase", "DynamoDB", "Firebase", "Supabase", "Redis", "Memcached", "Elasticsearch",
  "Prisma", "TypeORM", "Sequelize", "Mongoose", "Docker", "Kubernetes", "Docker Compose",
  "AWS", "Google Cloud", "Microsoft Azure", "Heroku", "Vercel", "Netlify", "DigitalOcean",
  "Terraform", "Ansible", "Chef", "Puppet", "Jenkins", "GitHub Actions", "GitLab CI",
  "CircleCI", "Travis CI", "Bitbucket Pipelines", "Linux", "Unix", "Bash", "PowerShell",
  "Nginx", "Apache", "Kafka", "RabbitMQ", "ActiveMQ", "gRPC", "WebSockets", "Socket.io",
  "Microservices", "Serverless", "Machine Learning", "Deep Learning", "Data Science",
  "TensorFlow", "PyTorch", "Pandas", "NumPy", "Scikit-Learn", "Computer Vision",
  "NLP", "Data Engineering", "Hadoop", "Spark", "Airflow", "BlockChain", "Solidity",
  "Web3.js", "Ethers.js", "Smart Contracts", "IoT", "AR/VR", "Unity", "Unreal Engine",
  "UI/UX Design", "Figma", "Adobe XD", "Sketch", "Agile", "Scrum", "Kanban", "Jira",
  "Confluence", "Git", "GitHub", "GitLab", "Bitbucket"
].sort(); // Sort alphabetically for easier finding
